hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

env:
  config:
    PORT: "8080"
    REDIS_HOST: sweetflags-redis.dev.gcp.sweetwater.com
    REDIS_PORT: "6379"
    AUTH0_DOMAIN: dev-sweetwater-internal.us.auth0.com
    AUTH0_API_IDENTIFIER: urn:sweetflags-api
    AUTH0_CLIENT_ID: 4oE6I2AfQ7IFN9wA41hwOghCpHL2gJ5V
    NODE_ENV: ${ENVIRONMENT}
    npm_config_cache: /tmp
  secrets:
    MONGODB_URI: "mongodb://sweetflags:${MONGODB_PASSWORD}@mongodb-sweetflags-headless.sweetflags.svc.cluster.local:27017/sweetflags?replicaSet=rs0"
    MONGODB_PASSWORD: "${MONGODB_PASSWORD}"

datadog:
  labels:
    admission.datadoghq.com/enabled: "true"
    tags.datadoghq.com/service: "sweetflags"
    tags.datadoghq.com/env: ${ENVIRONMENT}
  annotations:
    ad.datadoghq.com/tags: '{"team": "production-support"}'

livenessProbe:
  httpGet:
    path: /api/healthz
    port: 8080
readinessProbe:
  httpGet:
    path: /api/healthz
    port: 8080

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

redis:
  enabled: true
  name: sweetflags
  memorySizeGb: 2
  authEnabled: true

mongodb:
  enabled: true
  name: mongodb-sweetflags
  version: 'v6'
  auth:
    replicaSetKey: "${MONGODB_REPLICA_SET_KEY}"
    rootPassword: "${MONGODB_ROOT_PASSWORD}"
    usernames:
      - sweetflags
    passwords:
      - "${MONGODB_PASSWORD}"
    databases:
      - sweetflags

  externalAccess:
    enabled: true
