include:
  - project: 'it/devops/ci-templates'
    file: 
      - 'gitlab-deployment.yaml'
      - 'stages/scan/mono_repo_scan.yaml'
    ref: gl-deploy-v1
  - local: sweetflags-api/.gitlab-ci.yml
  - local: sweetflags-ui/.gitlab-ci.yml
    # ref: gl-deploy-v1

stages:
  - build
  - image_scan
  - deploy
