include:
  - project: 'it/devops/ci-templates'
    file: 
      - 'gitlab-deployment.yaml'
      - 'stages/scan/mono_repo_scan.yaml'
    ref: gl-deploy-v1
  - local: sweetflags-api/.gitlab-ci.yml
  - local: sweetflags-ui/.gitlab-ci.yml

variables:
  APP_OWNER: fourd_production_support_team
  APP_DOMAIN: fourd

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      variables:
        TARGET_CLUSTER: 'dev-mis_k8s-cluster'
        SECRET_ENV: dev
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        TARGET_CLUSTER: 'prod-mis_k8s-cluster'
        SECRET_ENV: prod

stages:
  - build
  - image_scan
  - deploy
