version: '3.8'
services:
  app:
    build: .
    image: sweetflags
    container_name: sweetflags
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://sweetflags-mongo:27017/sweetflags
    env_file: .env
    depends_on:
      - sweetflags-mongo
      - sweetflags-redis

  sweetflags-mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  sweetflags-redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:

