before_script:
    - > 
        if [ "$CI_COMMIT_BRANCH" = "main" ]; then
            export BUILD_MODE="production"
        else
            export BUILD_MODE="development"
        fi

build_ui:
  extends: .build_default_registry
  variables:
    IMAGE_NAME: 'ui'
    DOCKERFILE: $CI_PROJECT_DIR/sweetflags-ui/Dockerfile
    CONTEXT: $CI_PROJECT_DIR/sweetflags-ui
    BUILD_ARGS: "--build-arg BUILD_MODE=$BUILD_MODE"
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - .gitlab-ci.yml
        - helm/ui/*
        - sweetflags-ui/**/*

scan_ui:
  extends: .container_scanning
  variables:
    IMAGE_NAME: 'ui'

.deploy_ui:
  extends: .gitlab_helm_deploy
  variables:
    IMAGE_NAME: 'ui'
    HELM_RELEASE_NAME: 'sweetflags-ui'
    BASE_VALUES_DIR: 'helm/ui'

deploy_ui_dev:
  extends: .deploy_ui
  needs:
    - job: deploy_api_dev
      optional: true
  variables:
    SECRET_ENV: dev
  rules:
    - if: $CI_COMMIT_BRANCH == 'development'
      changes:
        - .gitlab-ci.yml
        - helm/ui/*
        - sweetflags-ui/**/*
  tags:
    - gitlab-helm-deploy
    - dev-mis_k8s-cluster

deploy_ui_prod:
  extends: .deploy_ui
  needs:
    - job: deploy_api_prod
      optional: true
  variables:
    SECRET_ENV: prod
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
        - .gitlab-ci.yml
        - helm/ui/*
        - sweetflags-ui/**/*
  tags:
    - gitlab-helm-deploy
    - prod-mis_k8s-cluster