version: '3.8'

services:
  sweetflags-ui:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: development
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - '/app/node_modules'