global:
  mongoService: "mongodb-sweetflags"

env:
  config:
    MONGODB_URI: mongodb-sweetflags-headless.sweetflags.svc.cluster.local:27017/sweetflags
    REDIS_HOST: ocalhost
    REDIS_PORT: 6379
    AUTH0_DOMAIN: dev-sweetwater-internal.us.auth0.com
    AUTH0_API_IDENTIFIER: urn:sweetflags-api
    AUTH0_CLIENT_ID: 4oE6I2AfQ7IFN9wA41hwOghCpHL2gJ5V
    NODE_ENV: ${ENVIRONMENT}
    npm_config_cache: /tmp
  secrets:
    MONGODB_PASSWORD: "${MONGODB_PASSWORD}"

datadog:
  labels:
    admission.datadoghq.com/enabled: "true"
    tags.datadoghq.com/service: "my-app"
    tags.datadoghq.com/env: ${ENVIRONMENT}
  annotations:
    ad.datadoghq.com/tags: '{"team": "production-support"}'

livenessProbe:
  httpGet:
    path: /healthz
    port: 3000
readinessProbe:
  httpGet:
    path: /healthz
    port: 3000

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

redis:
  enabled: true
  name: sweetflags
  memorySizeGb: 2
  authEnabled: true

mongodb:
  enabled: true
  datadogPassword: "${MONGODB_DATADOG_PASSWORD}"
  version: 'v6'
  auth:
    replicaSetKey: "${MONGODB_REPLICA_SET_KEY}"
    rootPassword: "${MONGODB_ROOT_PASSWORD}"
    usernames:
      - sweetflags
    passwords:
      - "${MONGODB_PASSWORD}"
    databases:
      - sweetflags
