build_api:
  extends: .build_default_registry
  variables:
    IMAGE_NAME: 'api'
    DOCKERFILE: $CI_PROJECT_DIR/sweetflags-api/Dockerfile
    CONTEXT: $CI_PROJECT_DIR/sweetflags-api
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - .gitlab-ci.yml
        - helm/api/*
        - sweetflags-api/**/*

scan_api:
  extends: .container_scanning
  variables:
    IMAGE_NAME: 'api'

deploy_api:
  extends: .gitlab_helm_deploy
  needs: [ build_api ]
  variables:
    IMAGE_NAME: 'api'
    BASE_VALUES_DIR: 'helm/api'
    HELM_MONGO_CHART_VERSION: '6.1.0'
  secrets:
    MONGODB_PASSWORD:
      vault: "${SECRET_ENV}/production-support/sweetflags/env/MONGODB_PASSWORD@secret"
      file: false
    MONGODB_REPLICA_SET_KEY:
      vault: "${SECRET_ENV}/production-support/sweetflags/env/MONGODB_REPLICA_SET_KEY@secret"
      file: false
    MONGODB_ROOT_PASSWORD:
      vault: "${SECRET_ENV}/production-support/sweetflags/env/MONGODB_ROOT_PASSWORD@secret"
      file: false
  rules:
    - if: $CI_COMMIT_BRANCH == 'development' || $CI_COMMIT_BRANCH == 'main'
      changes:
        - .gitlab-ci.yml
        - helm/api/*
        - sweetflags-api/**/*
  tags:
    - gitlab-helm-deploy
    - $TARGET_CLUSTER
