build_api:
  extends: .build_default_registry
  variables:
    IMAGE_NAME: 'api'
    DOCKERFILE: $CI_PROJECT_DIR/sweetflags-api/Dockerfile
    CONTEXT: $CI_PROJECT_DIR/sweetflags-api
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - .gitlab-ci.yml
        - helm/api/*
        - sweetflags-api/**/*

scan_api:
  extends: .container_scanning
  variables:
    IMAGE_NAME: 'api'

.deploy_api:
  extends: .gitlab_helm_deploy
  needs:
    - build_api
  variables:
    IMAGE_NAME: 'api'
    BASE_VALUES_DIR: 'helm/api'
  secrets:
    MONGODB_DATADOG_PASSWORD:
      vault: "shared/gke-mongodb-${SECRET_ENV}/datadog-token@secret"
      file: false
    MONGODB_PASSWORD:
      vault: "${SECRET_ENV}/production-support/sweetflags/env/MONGODB_PASSWORD@secret"
      file: false
    MONGODB_REPLICA_SET_KEY:
      vault: "${SECRET_ENV}/production-support/sweetflags/env/MONGODB_REPLICA_SET_KEY@secret"
      file: false
    MONGODB_ROOT_PASSWORD:
      vault: "${SECRET_ENV}/production-support/sweetflags/env/MONGODB_ROOT_PASSWORD@secret"
      file: false
    PDNS_API_KEY:
      vault: "shared/power-dns-${SECRET_ENV}-mis/PDNS_API_KEY@secret"
      file: false
    TLS_CRT:
      vault: "shared/${SECRET_ENV}-gcp-letsencrypt/cert@secret"
      file: false
    TLS_KEY:
      vault: "shared/${SECRET_ENV}-gcp-letsencrypt/key@secret"
      file: false

deploy_api_dev:
  extends: .deploy_api
  variables:
    SECRET_ENV: dev
  rules:
    - if: $CI_COMMIT_BRANCH == 'development'
      changes:
        - .gitlab-ci.yml
        - helm/api/*
        - sweetflags-api/**/*
  tags:
    - gitlab-helm-deploy
    - dev-mis_k8s-cluster

deploy_api_prod:
  extends: .deploy_api
  variables:
    SECRET_ENV: prod
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
        - .gitlab-ci.yml
        - helm/api/*
        - sweetflags-api/**/*
  tags:
    - gitlab-helm-deploy
    - prod-mis_k8s-cluster
