apiVersion: apps/v1
kind: Deployment
metadata:
  name: sweetflags-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sweetflags-api
  template:
    metadata:
      labels:
        app: sweetflags-api
    spec:
      containers:
      - name: sweetflags-api
        image: us-central1-docker.pkg.dev/sweetflags/sweetflags/sweetflags-api
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri
              key: MONGODB_URI
        ports:
        - containerPort: 8080