apiVersion: apps/v1
kind: Deployment
metadata:
  name: sweetflags-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sweetflags-api
  template:
    metadata:
      labels:
        app: sweetflags-api
    spec:
      containers:
      - name: sweetflags-api
        image: $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
        ports:
        - containerPort: 8080