apiVersion: v1
kind: Service
metadata:
  name: sweetflags-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: sweetflags-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
