apiVersion: v1
kind: Service
metadata:
  name: sweetflags-api
spec:
  containers:
    - name: sweetflags-api
      image: sweetflags-api
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 20
